# Generated by Django 5.2.7 on 2025-10-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Μέση Αξιολόγηση'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_completed_transactions',
            field=models.PositiveIntegerField(default=0, verbose_name='Ολοκληρωμένες Συναλλαγές'),
        ),
    ]
