# Generated by Django 5.2.7 on 2025-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Αστέρια (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Σχόλιο')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Αξιολόγηση',
                'verbose_name_plural': 'Αξιολογήσεις',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('exchange', 'Ανταλλαγή'), ('loan', 'Δανεισμός'), ('either', 'Ανταλλαγή ή Δανεισμός')], max_length=10, verbose_name='Τύπος συναλλαγής')),
                ('message', models.TextField(blank=True, verbose_name='Μήνυμα')),
                ('status', models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('pending_terms', 'Εκκρεμεί αποδοχή όρων'), ('pending_confirmation', 'Εκκρεμεί επιβεβαίωση'), ('accepted', 'Ενεργή'), ('rejected', 'Απορριφθείσα'), ('cancelled', 'Ακυρωμένη'), ('completed', 'Ολοκληρωμένη')], default='pending', max_length=30, verbose_name='Κατάσταση')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Έναρξη δανεισμού')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Λήξη δανεισμού')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία επιστροφής')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Όροι Δανεισμού')),
                ('borrower_accepted_terms', models.BooleanField(default=False, verbose_name='Αποδοχή Όρων από Αιτούντα')),
                ('delivery_method', models.CharField(blank=True, max_length=20, null=True)),
                ('meeting_lat', models.FloatField(blank=True, null=True)),
                ('meeting_lng', models.FloatField(blank=True, null=True)),
                ('meeting_status', models.CharField(choices=[('none', 'Καμία'), ('proposed', 'Προτάθηκε'), ('accepted', 'Αποδεκτή'), ('rejected', 'Απορρίφθηκε')], default='none', max_length=20)),
            ],
            options={
                'verbose_name': 'Συναλλαγή',
                'verbose_name_plural': 'Συναλλαγές',
                'ordering': ['-created_at'],
            },
        ),
    ]
