# Generated by Django 5.2.7 on 2025-10-07 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_itemimage_options_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Συναλλαγή', 'verbose_name_plural': 'Συναλλαγές'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='items.item', verbose_name='Αντικείμενο'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, verbose_name='Μήνυμα'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Ιδιοκτήτης'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Αιτών'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('accepted', 'Αποδεκτή'), ('rejected', 'Απορριφθείσα'), ('cancelled', 'Ακυρωμένη')], default='pending', max_length=10, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('exchange', 'Ανταλλαγή'), ('loan', 'Δανεισμός')], max_length=10, verbose_name='Τύπος συναλλαγής'),
        ),
    ]
