# Generated by Django 5.2.7 on 2025-10-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requester_completed',
            field=models.BooleanField(default=False),
        ),
    ]
