# Generated by Django 5.2.7 on 2025-10-08 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_itemimage_options_and_more'),
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Λήξη δανεισμού'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requested_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_offers', to='items.item', verbose_name='Αντικείμενο προς ανταλλαγή'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Έναρξη δανεισμού'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('accepted', 'Αποδεκτή'), ('rejected', 'Απορριφθείσα'), ('cancelled', 'Ακυρωμένη'), ('completed', 'Ολοκληρωμένη')], default='pending', max_length=10, verbose_name='Κατάσταση'),
        ),
    ]
