# Generated by Django 5.2.7 on 2025-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_end_date_transaction_requested_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('exchange', 'Ανταλλαγή'), ('loan', 'Δανεισμός'), ('either', 'Ανταλλαγή ή Δανεισμός')], max_length=10, verbose_name='Τύπος συναλλαγής'),
        ),
    ]
