# Generated by Django 5.2.7 on 2025-10-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_owner_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meeting_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
