# Generated by Django 5.2.7 on 2025-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία επιστροφής'),
        ),
    ]
