# Generated by Django 5.2.7 on 2025-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_meeting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requester_received',
            field=models.BooleanField(default=False),
        ),
    ]
