# Generated by Django 5.2.7 on 2025-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_owner_shipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='owner_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requester_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
