# Generated by Django 5.2.7 on 2025-10-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='borrower_accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Αποδοχή Όρων από Αιτούντα'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Όροι Συμφωνίας'),
        ),
    ]
