# Generated by Django 5.2.7 on 2025-10-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_borrower_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('pending_terms', 'Εκκρεμεί αποδοχή όρων'), ('pending_confirmation', 'Εκκρεμεί επιβεβαίωση'), ('accepted', 'Ενεργή'), ('rejected', 'Απορριφθείσα'), ('cancelled', 'Ακυρωμένη'), ('completed', 'Ολοκληρωμένη')], default='pending', max_length=30, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Όροι Δανεισμού'),
        ),
    ]
