# Generated by Django 5.2.7 on 2025-10-09 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_status_alter_transaction_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Αστέρια (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Σχόλιο')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Αξιολογούμενος')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Αξιολογητής')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transactions.transaction', verbose_name='Συναλλαγή')),
            ],
            options={
                'verbose_name': 'Αξιολόγηση',
                'verbose_name_plural': 'Αξιολογήσεις',
                'ordering': ['-created_at'],
                'unique_together': {('transaction', 'reviewer')},
            },
        ),
    ]
