# Generated by Django 5.2.7 on 2025-10-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('items', '0003_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='items.item'),
        ),
    ]
