# Generated by Django 5.2.7 on 2025-10-14 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('exchange', 'Ανταλλαγή'), ('loan', 'Δανεισμός'), ('either', 'Ανταλλαγή ή Δανεισμός')], default='exchange', max_length=10, verbose_name='Τύπος συναλλαγής')),
                ('category', models.CharField(choices=[('electronics', 'Ηλεκτρονικά'), ('books', 'Βιβλία'), ('clothing', 'Ρούχα'), ('furniture', 'Έπιπλα'), ('sports', 'Αθλητικά'), ('tools', 'Εργαλεία'), ('other', 'Άλλο')], default='other', max_length=30, verbose_name='Κατηγορία')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Προεπιλεγμένοι Όροι Διάθεσης')),
                ('delivery_method', models.CharField(choices=[('in_person', 'Χέρι με χέρι'), ('shipping', 'Αποστολή με courier'), ('pickup_point', 'Σημείο συνάντησης'), ('other', 'Άλλο')], default='in_person', max_length=20, verbose_name='Τρόπος Παράδοσης')),
            ],
            options={
                'verbose_name': 'Αντικείμενο',
                'verbose_name_plural': 'Αντικείμενα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Εικόνα αντικειμένου',
                'verbose_name_plural': 'Εικόνες αντικειμένων',
            },
        ),
    ]
