# Generated by Django 5.2.7 on 2025-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Προβολές'),
        ),
    ]
