# Generated by Django 5.2.7 on 2025-10-07 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'Αντικείμενο', 'verbose_name_plural': 'Αντικείμενα'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Εικόνα αντικειμένου', 'verbose_name_plural': 'Εικόνες αντικειμένων'},
        ),
        migrations.AddField(
            model_name='itemimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Ιδιοκτήτης'),
        ),
    ]
