# Generated by Django 5.2.7 on 2025-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='transaction_type',
            field=models.CharField(choices=[('exchange', 'Ανταλλαγή'), ('loan', 'Δανεισμός'), ('either', 'Ανταλλαγή ή Δανεισμός')], default='exchange', max_length=10, verbose_name='Τύπος συναλλαγής'),
        ),
    ]
