# Generated by Django 5.2.7 on 2025-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='terms',
            field=models.TextField(blank=True, null=True, verbose_name='Προεπιλεγμένοι Όροι Διάθεσης'),
        ),
    ]
