# Generated by Django 5.2.7 on 2025-10-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Ηλεκτρονικά'), ('books', 'Βιβλία'), ('clothing', 'Ρούχα'), ('furniture', 'Έπιπλα'), ('sports', 'Αθλητικά'), ('tools', 'Εργαλεία'), ('other', 'Άλλο')], default='other', max_length=30, verbose_name='Κατηγορία'),
        ),
    ]
