# Generated by Django 5.2.7 on 2025-10-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery_method',
            field=models.CharField(choices=[('in_person', 'Χέρι με χέρι'), ('shipping', 'Αποστολή με courier'), ('pickup_point', 'Σημείο συνάντησης'), ('other', 'Άλλο')], default='in_person', max_length=20, verbose_name='Τρόπος Παράδοσης'),
        ),
    ]
